services:
  graphql-server:
    build: .
    container_name: raza-ag
    command: sh -c "npm install && npm run dev"
    ports:
      - "4000:4000"
    volumes:
      - .:/app 
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    networks:
      - autenticador_network

networks:
  autenticador_network:
    external: true
