services:
  graphql-server:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/app 
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    command: npm run dev
    networks:
      - autenticador_network

networks:
  autenticador_network:
    external: true
